### ISSUE TITLE
Agent Availability Signaling Tool

### ISSUE THREAD

**Issue by dOrgJelli** [dOrgTech/Ecosystem#36]
### Description
A solution to track the availability of agent resources.
Create a Keybase bot that pings agents periodically to provide their desired work availability.
Create an application to store this information and a front-end to visualize it.

### Potential Implementation
1. Create a Keybase chat bot that pings agent users on dOrg's Keybase server, on a configurable periodic basis to provide or reaffirm their desired Work Level (see #19 ) commitment
2. Store agent identification, their Work Level, and when it was provided in a database
3. Create a front-end that provides visualization of this stored data

Bonus points: Use a distributed storage system instead of a traditional database

### Relevant Documentation
https://github.com/keybase/keybase-bot/blob/master/demos/math-bot.js

### Funding Request
$1,000 ([Proposal Pending](https://alchemy.daostack.io/dao/0x15344ecdc2c4edfcb092e284d93c20f0529fd8a6/proposal/0x6a7bc9d4cc30e9afe5c900e411ab426bb81f0069e5793c528711f0d0b9fdcc52))

**Comment by nickplace** [comment]
Could be a chatbot that operates through Discord that pings you every week/month about your upcoming availability. And then an app to visualize everything.

**Comment by benefacto** [comment]
@dOrgJelli I'm quite interested in this one. At what point would it be decided whether or not this bounty gets funded?

**Comment by dOrgJelli** [comment]
Awesome @benefacto! So in order to get it funded, we'd create a proposal in the DAO and ask the group to vote on allocating the funds for this task's bounty. Here's an example issue where this was done (see Funding section): https://github.com/dOrgTech/Ecosystem/issues/16

I think the first step is to decide what the spec for the deliverable is. Do you have something in mind?

**Comment by benefacto** [comment]
Hi @dOrgJelli, thanks for getting back to me! I'm thinking so far this bounty seems like the best place for me to start if I can get it funded. Weekdays are super busy for me as of late so I'm planning on sharing what I was thinking the coming weekend.

**Comment by dOrgJelli** [comment]
Okay sounds great @benefacto! Please let me know if I can help in any way. You can contact me on Telegram or Keybase @dOrgJelli

**Comment by benefacto** [comment]
Hey @dOrgJelli, here's what I got so far from going off the other bounties as examples. Feel free let me know if you believe any revisions or additions would be useful.

### Description
dOrg needs a solution to track the availability of agent resources.
Create a Discord bot that pings agents periodically to provide their desired work availability.
Create an application to store this information and a front-end to visualize it.

### Potential Implementation
1. Create a Discord chat bot that pings agent users on dOrg's Discord server, on a configurable periodic basis to provide or reaffirm their desired Work Level (see #19 ) commitment
2. Store agent identification, their Work Level, and when it was provided in a database
3. Create a front-end that provides visualization of this stored data

Bonus points: Use a distributed storage system instead of a traditional database

### Relevant Documentation
https://www.howtogeek.com/364225/how-to-make-your-own-discord-bot/
https://discordapi.com/unofficial/libs.html

### Funding Request
$1,000

**Comment by dOrgJelli** [comment]
Sounds great @benefacto! The only edit I would make is to make a keybase bot instead as we've migrated over to that platform. Here's an example bot: https://github.com/keybase/keybase-bot/blob/master/demos/math-bot.js

I've changed the description above to reflect yours. I also posted the proposal to the DAO: https://alchemy.daostack.io/dao/0x15344ecdc2c4edfcb092e284d93c20f0529fd8a6/proposal/0x6a7bc9d4cc30e9afe5c900e411ab426bb81f0069e5793c528711f0d0b9fdcc52
