### ISSUE TITLE
Dequity Redemption Scheme

### ISSUE THREAD

**Issue by orishim** [dOrgTech/Ecosystem#42]
# Description

Develop smart contracts for the dOrg Token redemption flow. 

# Suggested Implementation

dOrg sends various tokens to the redemption contract. dOrg tokens can be redeemed against the redemption contract for a fractional share of the tokens it holds.

# Relevant Code

[Moloch v2](https://github.com/MolochVentures/moloch)

# Other Considerations

- How does time work? Need to have higher proportional claim the longer you hodl.
- How does redemption work? Burning your tokens give you fractional share of all the different assets in the redemption contract?

# Impact
- Reward contributors for going long on dOrg: Token-holders are incentivized to think from a long-term health perspective
- Get more done with less resources: If people are willing to work for dOrg tokens, we have more cash-on-hand to deploy towards internal projects & growth

**Comment by tspoff** [comment]
I'd be interested in taking this on as a side project - I have an idea of how it could work, inspired by the DSR. 

Will need to read up on Moloch v2 stuff to see what's going on there.

**Comment by cbrzn** [comment]
@tspoff would be glad to help you in any way I can!

**Comment by tspoff** [comment]
So I thought about this a bit, and mapped out how it could work.

## Possible Implementation
* dOrg tokens are continuously increasing in value ("accumulating interest"), using MakerDAO moon math from the DSR.
  * There is a single interest rate, which can be set by DAO vote
* These tokens can be redeemed for other currencies using a mechanism of our choice at one or more *special wallets* called **X** (taking name suggestions - something involving security, growth, and optimistic forward-looking inclination, and / or catchy and distinct)
  * These wallets are funded by the DAO manually, for now


## How Wallets Work
Two options:
As specified above: At any time, a dOrg token holder can burn tokens to receive a part of the current funds in the Wallet in proportion to the current totalSupply of dOrg tokens.

You could also have a normal 'exchange rate' at a wallet. This wallet would probably use Oracles to determine fair pricing of the assets within.

The nice thing about the wallet-focused architecture is we can stop using one and deploy a new wallet for new features as the spec evolves. 

* All existing tokens will be considered issued at time 0, and start accumulating interest when the system is deployed
* Users can claim funds via a simple interface, in alchemy or otherwise.

Happy for comments / questions!

**Comment by dOrgJelli** [comment]
Sounds amazing @tspoff! I think the *special wallets* could be called "Reward Wallets" or something like that :P

Having the "global" interest rate is interesting, but I also think it's interesting thinking about this more local to the *special wallets*. What if each wallet has their own redemption token that you can swap your dOrg token for. That redemption token could then have a set interest rate for the longer you hold it.

IMO the first user scenario that sounds very useful is:
- Create a "Reward Wallet" that works for a list of stable coins (USDC, DAI, etc), call this `StableReturn`.
- `StableReturn` has a return rate of 1.5x per year, and a cap of 3x.
- Users can claim their reward from this wallet whenever they'd like.
- To ensure users couldn't drain all the funds, leaving others unable to claim, redemptions would be capped based on the total outstanding tokens that're circulating.

^^^ I think the above could be implemented w/ the moon logic you described, but I'm unsure.

**Comment by dOrgJelli** [comment]
The DSR makes sense @tspoff. Here are some additional thoughts:
- I think the interest yielding token & dOrg token should be separate. Maybe you get the *special wallet*'s token by wrapping or burning your dOrg token.
- Thinking more about implementing the cap makes my head hurt... problems are introduced when you think about transferring these tokens, and also changing interest rates.
- Instead of having a cap to ensure we don't put ourselves too far into debt, we could just choose to set the interest rate very low. The scenario I'm trying to prevent is having someone hold onto a bunch of tokens for a long time, and then claim a ridiculous amount of funds. I suppose that if we implement the redeem in a way where they couldn't take a disproportionate amount of the available funds so others couldn't also cash out, then this would fix the issue.

**Comment by pimato** [comment]
> Instead of having a cap to ensure we don't put ourselves too far into debt, we could just choose to set the interest rate very low. The scenario I'm trying to prevent is having someone hold onto a bunch of tokens for a long time, and then claim a ridiculous amount of funds. I suppose that if we implement the redeem in a way where they couldn't take a disproportionate amount of the available funds so others couldn't also cash out, then this would fix the issue.

I believe the job for dorg will be to maintain a healthy interest rate to assure we are not getting into debt. If we believe we are heading into bad times without income, the interest rate should decrease to 0%. I believe a cap is not the right way here. Your point about a person who will hold the dOrg token for a long time and then claim a ridiculous amount of funds: This should be totally fine as the person put a long bet which should be rewarded accordingly and most importantly the math will do its job for a fair distribution of rewards.

**Comment by pimato** [comment]
I am a little bit confused about the "Wallet" thing which we probably should name differently as I consider a wallet an ethereum address. 

So it is basically a contract which holds collateral deposit by dOrg right? 

Will dOrg mint the dorg token from the dao? How does the connection between the dorg DAO and the wallet looks like? Seems like we just send collateral into wallets right?
Could you please go a little bit

**Comment by tspoff** [comment]
> So it is basically a contract which holds collateral deposit by dOrg right?

Yea, that's what it is. It also defines a set of rules for withdrawing that collateral, including who can withdraw, how much, when, and how to value dOrg tokens. Request for naming is still open :)

It's kind of an AMM for dOrg tokens with fancy rules.

> Will dOrg mint the dorg token from the dao? How does the connection between the dorg DAO and the wallet looks like? Seems like we just send collateral into wallets right?

With the wallet-based system, the dOrg token can stay like it is as a normal ERC20 minted from the DAO, and the interest stuff lives in the wallet mechanics.

* The DAO creates & owns the wallets
* The DAO sends collateral to them

**Comment by orishim** [comment]
Here is another approach:
- DAO can set global interest rate
- Anyone can lock their dOrg Tokens to start earning additional dOrg tokens according to the interest rate
- Rewards contract only holds DAI, redeemable 1-to-1 with dOrg tokens

**Comment by dOrgJelli** [comment]
This sounds like a great approach @orishim :D

**Comment by orishim** [comment]
New thinking from the call today:

Redemption contract has these functions:

1. **Stake(uint amount)**: Tokens sent to the contract using this method tokens begin to compound according to `global_interest_rate`

2. **Burn(uint amount)**: Burns tokens and returns equivalent amount of USDC to sender. What if there is not enough USDC? Two possibilities:
    - transaction just reverts; this is the simpler option
    - tokens enter a pending queue, which means they stop compounding and will be redeemable once there is enough USDC
 
Tokens that are not staked or pending in this contract are just regular erc-20, they can be transferred but do not compound.
