### ISSUE TITLE
Budget blocks App

### ISSUE THREAD

**Issue by orishim** [dOrgTech/Ecosystem#43]
# Description

Continue work on budget blocks app.

Budget blocks visualizes revenue and expense flows across the organization to aid agents in decision-making. 

# Suggested Implementation
.. 

# Relevant Code 
https://github.com/dOrgTech/budgetBlocks

# Impact
- Reduce administrative + cognitive overhead 
- Increase transparency + predictability

**Comment by orishim** [comment]
@cbrzn Here is what I'm thinking with budget block flow.

### Initialize New Project

dOrg ratifies a Statement of Work, which specifies the:
- `income_schedule` array of (date, amount) events
- `payout_schedule` array of (date, amount) events
- `save_rate` the difference between the sum of all income and payouts

### Income

For every income event,

1. dOrg invoices Client
2. Client pays dOrg
3. Update balances
    - `Project_Balance += amount * (1 – save_rate)`
    - `dOrg_Balance += amount * save_rate`

### Payouts

For every payout event,

1. Agents invoice dOrg `[work_log, allocation_claim, defer_rate]`
2. Discussion and adjustments
    - agents see each other’s invoices, comment, and adjust until there is unanimous sign-off
    - if there is stalemate, broader DAO arbitrates
3. dOrg pays Agents
    - `Rep = amount*allocation_claim/total_allocation_claim`
    - `Tokens = Rep*defer_rate`
    - `Payout = Rep – Tokens`
4. Update balances
    - `Project_Balance –= amount`
    - `dOrg_Balance += total_tokens`

**Comment by dOrgJelli** [comment]
Yep this sounds great! Here are some thoughts on the user-flow for these 3 use-cases:

## Initialize New Project
1. Open Budget Blocks & Log In (Airtable OAuth W/ @dorg.tech Address)
2. Click "Add Budget"
3. Fill-Out Info (income + payout schedule, saving rate)
4. When all details are filled out, user clicks the "Propose" button which makes a DAO proposal (all from within Budget Blocks ideally).
5. Proposal ID is automatically logged in the form, and the form is submitted to Air Table.

After this process, the budget would be added to a "pending" section. When the proposal passes, the project will be moved into the "current/active" section.

## Income
1. When income event happens, an email notification is sent out to "operations@dorg.tech"
2. Someone from the operations team will then email the client with the invoice document.

An alternative is to automate this completely, and instead of emailing "operations@dorg.tech", we just email the client via their email that's set in the airtable.

3. Client pays dOrg, and an email is sent out to operations@dorg.tech saying a new payment was made to the DAO. If it's `from` a known address that tied to a client, the email can add that info.
4. Someone from operations will need to fill out the transactions details.
5. Once the details are set (client, amount, project, etc), the budget blocks app will automatically be updated since it's reading from AirTable.

## Payouts
Nothing to really add here :P

**Comment by cbrzn** [comment]
> When all details are filled out, user clicks the "Propose" button which makes a DAO proposal (all from within Budget Blocks ideally).

DAOComponents? :P

>3. Client pays dOrg, and an email is sent out to operations@dorg.tech saying a new payment was made to the DAO. If it's from a known address that tied to a client, the email can add that info. 
>4. Someone from operations will need to fill out the transactions details.

Here maybe we can add zappier to automate this?

Also - I'd say that we should develop this flow in parallel with the Redemption Contract, so in the payment workflow, as a fourth step, it can be that the tax rate is deposited into this contract(?)

**Comment by orishim** [comment]
I don’t think tax should be deposited anywhere. It is just an amount that is retained in the DAO. The DAO can periodically make proposals to move funds to the redemption contract as needed. 

For email, yes there is the Dagger zapier integration which can send an email and add new entries to the client income table for every incoming transaction. I messed around with this a bit and it was pretty easy to use.
